apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy.cloud.kuly/app: control-plane
  name: control-plane
  namespace: kuly-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy.cloud.kuly/app: control-plane
  template:
    metadata:
      labels:
        deploy.cloud.kuly/app: control-plane
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: control-plane
        ports:
        - containerPort: 12270
          name: rpc
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: kuly-platform
  name: control-plane
  labels: 
    deploy.cloud.kuly/app: control-plane
spec:
  selector:
    deploy.cloud.kuly/app: control-plane
  ports:
    - protocol: TCP
      port: 12270
      targetPort: 12270